### ISSUE TITLE
Page template caching

### ISSUE THREAD

**Issue by a-salihov** [networking/init-cms-bundle#31]
It seems that there is very hard caching of the page template.

For example:
My homepage had assigned my own template "Sandbox two-column homepage". 
    'Sandbox_two_column_homepage_template':template: "ApplicationNetworkingInitCmsBundle:Main:two_column_homepage.html.twig"

I decided to change for  this template a twig view and altered it in the config.yml.
    'Sandbox_two_column_homepage_template':
            template: "ApplicationNetworkingInitCmsBundle:Main:main.html.twig"

I couldn't get new template on public any ways. Only after changing template name and Symfony cache rebuilding, I got a new twig template on the public:
    'Homepage_template':
            template: "ApplicationNetworkingInitCmsBundle:Main:main.html.twig"

**Comment by ychadwick** [comment]
I am not sure what you question is.
When you create a page, the template used is inserted in the DB (content_route table). If you should change the name of the template, you will need to change the entries in the DB that should use the new template, only newly created pages will use the new template.

This is not caching, just simple old DB Data.

The reason for it is so that when a request comes in, and a route is found in the DB, the request is the filed with the correct _template and _controller variables, so that it can be used just like it came from a routing.yml file.
