### ISSUE TITLE
Caching of the image thumbnail

### ISSUE THREAD

**Issue by a-salihov** [networking/init-cms-bundle#32]
v2.5.6, admin section
Thumbnails of the images are cashed. For example, 
- in the media galleries: after picture changing we see old image.
- in the page template editing: when we created block with content "gallery:carousel". If the image has been changed in the gallery, it is not shown in the content block, we see old picture.

**Comment by ychadwick** [comment]
There are two aspects:
- your browser may be caching an image.
- if you change a gallery, you should see the change in page preview (if your browser doesn't cache the image). To see the change on the live page you need to republish the page. 

All published pages are kept as a serialized object with all there content, so if you change content outside of the page you need to republish the page so that it can reserialize the new content.

This is done so that the admin users can edit content without the stress that the live page will change before the new content has been approved.

**Comment by a-salihov** [comment]
Thanks, I understand about live page on the public, but I tell only about admin section.
There isn't any hash marker in the images names, so browser caches old pictures. It is not comfortable as for me.

Also, as for me, I would be comfortable to see:
- page status (published or not) for each translated page in the Translations list (right top panel while page editing)
- "delete" button in the media list
